import 'package:flutter/material.dart';
import 'package:resistance_calculator/logic/line_model.dart';

const Color kDarkBlueColor = Color(0xFF022F40);
const Color kLightBlueColor = Color(0xFF38AECC);
const Color kSelectedItemColor = Color(0xFF0090C1);

List<Line> listOfFiveLines = [
  Line(
    numberOfLine: 0,
    lineColor: Colors.transparent,
    tolerance: 20,
    avilableOnLines: [4],
  ),
  Line(
    numberOfLine: 1,
    lineColor: Colors.blueGrey,
    multiplier: 0.01,
    tolerance: 10,
    avilableOnLines: [3, 4],
  ),
  Line(
    numberOfLine: 2,
    lineColor: Colors.amberAccent,
    multiplier: 0.1,
    tolerance: 5,
    avilableOnLines: [3, 4],
  ),
  Line(
    numberOfLine: 3,
    lineColor: Colors.black,
    secondLineValue: 0,
    multiplier: 1,
    temperatureRate: 250,
    avilableOnLines: [2, 3, 5],
  ),
  Line(
    numberOfLine: 4,
    lineColor: Colors.brown,
    firstLineValue: 1,
    secondLineValue: 1,
    multiplier: 10,
    tolerance: 1,
    temperatureRate: 100,
    avilableOnLines: [1, 2, 3, 4, 5],
  ),
  Line(
    numberOfLine: 5,
    lineColor: Colors.red,
    firstLineValue: 2,
    secondLineValue: 2,
    multiplier: 100,
    tolerance: 2,
    temperatureRate: 50,
    avilableOnLines: [1, 2, 3, 4, 5],
  ),
  Line(
    numberOfLine: 6,
    lineColor: Colors.orange,
    firstLineValue: 3,
    secondLineValue: 3,
    multiplier: 1000,
    temperatureRate: 15,
    avilableOnLines: [1, 2, 3, 5],
  ),
  Line(
    numberOfLine: 7,
    lineColor: Colors.yellow,
    firstLineValue: 4,
    secondLineValue: 4,
    multiplier: 10000,
    temperatureRate: 25,
    avilableOnLines: [1, 2, 3, 5],
  ),
  Line(
    numberOfLine: 8,
    lineColor: Colors.green,
    firstLineValue: 5,
    secondLineValue: 5,
    multiplier: 100000,
    tolerance: 0.5,
    temperatureRate: 20,
    avilableOnLines: [1, 2, 3, 4, 5],
  ),
  Line(
    numberOfLine: 9,
    lineColor: Colors.blue,
    firstLineValue: 6,
    secondLineValue: 6,
    multiplier: 1000000,
    tolerance: 0.25,
    temperatureRate: 10,
    avilableOnLines: [1, 2, 3, 4, 5],
  ),
  Line(
    numberOfLine: 10,
    lineColor: Colors.purple,
    firstLineValue: 7,
    secondLineValue: 7,
    multiplier: 10000000,
    tolerance: 0.1,
    temperatureRate: 5,
    avilableOnLines: [1, 2, 3, 4, 5],
  ),
  Line(
    numberOfLine: 11,
    lineColor: Colors.grey,
    firstLineValue: 8,
    secondLineValue: 8,
    multiplier: 100000000,
    tolerance: 0.05,
    temperatureRate: 2,
    avilableOnLines: [1, 2, 3, 4, 5],
  ),
  Line(
    numberOfLine: 12,
    lineColor: Colors.white,
    firstLineValue: 9,
    secondLineValue: 9,
    multiplier: 1000000000,
    avilableOnLines: [1, 2, 3],
  ),
];

List<Line> listOfSixLines = [
  Line(
    numberOfLine: 0,
    lineColor: Colors.transparent,
    tolerance: 20,
    avilableOnLines: [5],
  ),
  Line(
    numberOfLine: 1,
    lineColor: Colors.blueGrey,
    multiplier: 0.01,
    tolerance: 10,
    avilableOnLines: [4, 5],
  ),
  Line(
    numberOfLine: 2,
    lineColor: Colors.amberAccent,
    multiplier: 0.1,
    tolerance: 5,
    avilableOnLines: [4, 5],
  ),
  Line(
    numberOfLine: 3,
    lineColor: Colors.black,
    secondLineValue: 0,
    multiplier: 1,
    temperatureRate: 250,
    avilableOnLines: [2, 3, 4, 6],
  ),
  Line(
    numberOfLine: 4,
    lineColor: Colors.brown,
    firstLineValue: 1,
    secondLineValue: 1,
    multiplier: 10,
    tolerance: 1,
    temperatureRate: 100,
    avilableOnLines: [1, 2, 3, 4, 5, 6],
  ),
  Line(
    numberOfLine: 5,
    lineColor: Colors.red,
    firstLineValue: 2,
    secondLineValue: 2,
    multiplier: 100,
    tolerance: 2,
    temperatureRate: 50,
    avilableOnLines: [1, 2, 3, 4, 5, 6],
  ),
  Line(
    numberOfLine: 6,
    lineColor: Colors.orange,
    firstLineValue: 3,
    secondLineValue: 3,
    multiplier: 1000,
    temperatureRate: 15,
    avilableOnLines: [1, 2, 3, 4, 6],
  ),
  Line(
    numberOfLine: 7,
    lineColor: Colors.yellow,
    firstLineValue: 4,
    secondLineValue: 4,
    multiplier: 10000,
    temperatureRate: 25,
    avilableOnLines: [
      1,
      2,
      3,
      4,
      6,
    ],
  ),
  Line(
    numberOfLine: 8,
    lineColor: Colors.green,
    firstLineValue: 5,
    secondLineValue: 5,
    multiplier: 100000,
    tolerance: 0.5,
    temperatureRate: 20,
    avilableOnLines: [1, 2, 3, 4, 5, 6],
  ),
  Line(
    numberOfLine: 9,
    lineColor: Colors.blue,
    firstLineValue: 6,
    secondLineValue: 6,
    multiplier: 1000000,
    tolerance: 0.25,
    temperatureRate: 10,
    avilableOnLines: [1, 2, 3, 4, 5, 6],
  ),
  Line(
    numberOfLine: 10,
    lineColor: Colors.purple,
    firstLineValue: 7,
    secondLineValue: 7,
    multiplier: 10000000,
    tolerance: 0.1,
    temperatureRate: 5,
    avilableOnLines: [1, 2, 3, 4, 5, 6],
  ),
  Line(
    numberOfLine: 11,
    lineColor: Colors.grey,
    firstLineValue: 8,
    secondLineValue: 8,
    multiplier: 100000000,
    tolerance: 0.05,
    temperatureRate: 2,
    avilableOnLines: [1, 2, 3, 4, 5, 6],
  ),
  Line(
    numberOfLine: 12,
    lineColor: Colors.white,
    firstLineValue: 9,
    secondLineValue: 9,
    multiplier: 1000000000,
    avilableOnLines: [1, 2, 3, 4],
  ),
];
